### ISSUE TITLE
新版本不怎么会用了。

### ISSUE THREAD

**Issue by lili21** [Jianru-Lin/SyntaxEditor#2]
能否提供一个老版本的呢？

**Comment by Jianru-Lin** [comment]
可以的。抱歉现在才看到。我会重新创建一个分支。

**Comment by wipphj** [comment]
你好,请问下这个在网页上使用时,目前是没有转到定义这个实现的吗?

**Comment by Jianru-Lin** [comment]
@wipphj 暂时没有实现。另外项目改到这里了 https://github.com/Jianru-Lin/lambda-view
