### ISSUE TITLE
谷歌上为什么保存不了？

### ISSUE THREAD

**Issue by hacke2** [Jianru-Lin/SyntaxEditor#3]
应该是保存到localstorage里吧，但是却没有

**Comment by Jianru-Lin** [comment]
正常情况下确实是保存在 localstorage 里的。没有保存成功吗？调试控制台里是否出现错误提示？谢谢。

**Comment by hacke2** [comment]
测试又好了，可能是我我之前看的那个源码太大了吧！赞！

**Comment by hacke2** [comment]
测试又好了，可能是我我之前看的那个源码太大了吧！赞！

**Comment by Jianru-Lin** [comment]
如果遇到问题欢迎随时提出 :)
