### ISSUE TITLE
Are the redundant spaces a bug?

### ISSUE THREAD

**Issue by redreamality** [Jianru-Lin/SyntaxEditor#4]
look at the below image, notice where the cursor is and where the last letter is, I haven't hit any spaces, however it renders the view like this. 
![image](http://i.imgur.com/whu3uRx.png)

**Comment by Jianru-Lin** [comment]
It seems like a bug. What webbrowser you use and what version it is? I tried that on my Chrome but nothing happened.

I found there is a problem in your image that the icon before the text didn't display correctlly. I guess there is some network error happened so some resources file not loaded. Maybe you can tell me more about that.

thanks a lot.

**Comment by redreamality** [comment]
ooops, I find out the problem, 
At first I also thought it was the network problem, until I banned all the extensions.
It seem to be an extension called "Force Microsoft Yahei Font" that recently installed causing the error, and sorry for the wrong bug report _(′_`」 ∠)_

now it's ok.
![](http://i.imgur.com/lAU14Bf.png)

**Comment by Jianru-Lin** [comment]
Good to hear that ^_^
